### ISSUE TITLE
How to load clip from transformers? 

### ISSUE THREAD

**Issue by CaffreyR** [slanj/ml-notebooks#1]
Hi @slanj, thanks for your article in the towardsdatascience. You have mentioned that the clip can be loaded from transformers now, so how to change the code here to achieve this? Thanks!

**Comment by slanj** [comment]
Hi. My code worked for me at that time, so I had no need to change it and I do not have a recipe how to use CLIP from transformers. You can figure out how to do it, just find code where CLIP weights are loaded and share your results with us.

**Comment by CaffreyR** [comment]
Hi @slanj , I see. BTW, I have tried to run your code but it seems wrong when load the model and inference.
```
Some weights of the model checkpoint at Hate-speech-CNERG/bert-base-uncased-hatexplain were not used when initializing BertModel: ['classifier.bias', 'classifier.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Model loaded from <== ./models/model-embs4-seq80-auc0.751-loss1.350-acc0.640.pt
  0%|          | 0/63 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "test.py", line 604, in <module>
    results = final_prediction(model, final_test_dataloader)
  File "test.py", line 547, in final_prediction
    for batch in tqdm(dataloader):
  File "/home/user/anaconda3/envs/meme/lib/python3.7/site-packages/tqdm/notebook.py", line 258, in __iter__
    for obj in it:
  File "/home/user/anaconda3/envs/meme/lib/python3.7/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/user/anaconda3/envs/meme/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/user/anaconda3/envs/meme/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/user/anaconda3/envs/meme/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/anaconda3/envs/meme/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "test.py", line 503, in __getitem__
    id = torch.LongTensor([self.data[index]["id"]])        
ValueError: too many dimensions 'str'
```
